# Default values for lets-chat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: arprasto/visualrecdemo
  tag: v1
  pullPolicy: Always
service:
  name: visualrecdemo
  tier: frontend
  type: NodePort
  protocol: TCP
  internalPort: 6111
  externalPort: 6111
  nodeport: 30092
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 128Mi
